---
# tasks file for nginx
- name: Add epel-release repo
  yum:
    name: epel-release
    state: present

- name: YUM install nginx
  yum:
    name: nginx
    state: present

- name: Create home directory for www
  file:
    path: "{{ nginx_index }}"
    state: directory

- name: setup virtual host app1
  template:
    src=app.j2
    dest={{ nginx_sites_centos }}/app.conf
